version: 2
jobs:
  build:
    working_directory: ~/sodo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          when: always
          name: Running Tests
          command: npm run test
      - store_test_results:
          path: ./reports/test
      - store_artifacts:
          path: ./reports/test
          destination: /reports/test
      - store_artifacts:
          path: ./reports/coverage
          destination: /reports/coverage
      - run:
          name: Linting
          command: npm run lint
          when: always
      - store_artifacts:
          path: ./reports/lint
          destination: /reports/lint
#      - run:
#          name: Checking Code Coverage
#          command: npm run check-coverage
